//
// This file was generated by TerraformSpawner, and any modification is likely to
// be lost after the next JupyterHub restart.
//
// The contents of this file can be customized through Jinja2 Template Inheritance.

//
// TerraformSpawner configured module
module "{{ spawner.get_module_id() }}" {
  {% block module_source %}
  source = "{{ spawner.tf_module }}"
  {% endblock %}
  {% block module_variables %}
  env = {
    {%- for k,v in spawner.get_env().items() %}
    {{ k }} = "{{ v }}",
    {%- endfor %}
  }
  {% endblock %}
}
{% block safety_valve %}{% endblock %}
