
{% set data = load_setup_py_data() %}

package:
  name: terraformspawner
  version: {{ data['version'] }}

source:
  path: ..

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - terraform
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {# raw is for ignoring templating with cookiecutter, leaving it for use with conda-build #}

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - pytest-asyncio
  commands:
    - pytest -v --color=yes tests

about:
  home: https://github.com/sodre/terraformspawner
  summary: Spawn JupyterHub single-user servers with Terraform
